#!/usr/bin/env bash
#
# Script to set colors generated by 'wal'
# https://github.com/dylanaraps/wal
# Source generated colors.
. "${HOME}/.cache/wal/colors.sh"

 reload_dunst() {
    pkill dunst
    dunst \
    -frame_width 2 \
        -lb "${color0}" \
        -nb "${color0}" \
        -cb "${color3}" \
        -lfr "${color6}" \
        -nfr "${color6}" \
        -cfr "${color0}" \
        -lf "${color6}" \
        -nf "${color6}" \
        -cf "${color6}" &
}

reload_dunst
